# Generated by Django 6.0.2 on 2026-02-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee_Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EMP_name", models.CharField(max_length=500)),
                ("EMP_DES", models.CharField(max_length=500)),
                ("EMP_place", models.CharField(max_length=500)),
                ("EMP_age", models.IntegerField()),
                ("EMP_salary", models.FloatField()),
            ],
        ),
    ]
