# Generated by Django 6.0.2 on 2026-02-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("usn", models.CharField(max_length=500)),
                ("branch", models.CharField(max_length=500)),
                ("sem", models.CharField(max_length=500)),
                ("Pnh_no", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
