# Generated by Django 6.0.2 on 2026-02-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0002_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="Pnh_no",
            new_name="phn_no",
        ),
    ]
