# Generated by Django 6.0.2 on 2026-02-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0003_rename_pnh_no_student_phn_no"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="student",
            new_name="student_Table",
        ),
    ]
